// FileIconOverlay.idl : IDL source for FileIconOverlay
//

// This file will be processed by the MIDL tool to
// produce the type library (FileIconOverlay.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(61982caa-30fc-4f28-9ba1-84ccb7ddd71d),
	version(1.0),
]
library FileIconOverlayLib
{
	importlib("stdole2.tlb");
};

